# ===================================================================
# LOCAL SPRING BOOT PROPERTIES
# ===================================================================

# ===================================================================
# APPLICATION
# ===================================================================
server.port: 1234

# ===================================================================
# LOGGING
# ===================================================================
logging.config: classpath:logback-spring.xml

# ===================================================================
# API
# ===================================================================
toss.api: 'https://api.tosspayments.com/v1/payments/'

spring.h2.console.enabled: true


