# ===================================================================
# LOCAL SPRING BOOT PROPERTIES
# ===================================================================

# ===================================================================
# APPLICATION
# ===================================================================
server.port: 9999

# ===================================================================
# LOGGING
# ===================================================================
logging.config: classpath:logback-spring.xml

# ===================================================================
# DATASOURCE 
# ===================================================================
#datasource:
#  url: jdbc:h2:mem:testdb

spring.h2.console.enabled: true


